insert into public.capstone_projects (
  id,
  title,
  abstract,
  author,
  year,
  department,
  tags,
  keywords,
  status,
  "originalityScore",
  created_at,
  updated_at
)
values
  (
    '10000000-0000-0000-0000-000000000001',
    'Smart Inventory Forecasting for Campus Cooperative Stores',
    'This study proposes a lightweight demand forecasting workflow for campus cooperative stores using historical sales, seasonal events, and supplier lead times. The system focuses on reducing stockouts and excess inventory through simple predictive models and an actionable dashboard for store managers.',
    'Allen M. Estrada',
    2024,
    'Business Administration',
    array['Inventory', 'Forecasting', 'Retail Analytics', 'Dashboard'],
    array['Inventory', 'Forecasting', 'Retail Analytics', 'Dashboard'],
    'approved',
    91,
    now() - interval '160 days',
    now() - interval '160 days'
  ),
  (
    '10000000-0000-0000-0000-000000000002',
    'Barangay Document Request Tracking via QR Verification',
    'The project designs a document request platform for barangay offices that tracks request status from intake to release. It combines QR-based claim verification, request logs, and turnaround-time reporting to reduce manual follow-up and improve citizen service visibility.',
    'Maria Dela Cruz',
    2024,
    'Information Technology',
    array['QR Code', 'E-Government', 'Workflow', 'Tracking'],
    array['QR Code', 'E-Government', 'Workflow', 'Tracking'],
    'approved',
    89,
    now() - interval '155 days',
    now() - interval '155 days'
  ),
  (
    '10000000-0000-0000-0000-000000000003',
    'Predictive Maintenance Alerts for Computer Laboratory Equipment',
    'This research builds a maintenance monitoring system for shared computer laboratory equipment using usage counts, fault logs, and component age. The application generates risk-based service alerts so staff can prioritize repairs before devices fail during class hours.',
    'John Paul Ramos',
    2023,
    'Information Technology',
    array['Predictive Maintenance', 'Laboratory', 'Asset Management', 'Alerts'],
    array['Predictive Maintenance', 'Laboratory', 'Asset Management', 'Alerts'],
    'approved',
    87,
    now() - interval '150 days',
    now() - interval '150 days'
  ),
  (
    '10000000-0000-0000-0000-000000000004',
    'Flood-Prone Route Recommendation for Student Commuters',
    'The study presents a mobile route recommendation tool that helps student commuters avoid flood-prone streets during heavy rainfall. It uses historical hazard areas, local advisories, and route scoring to recommend safer travel paths with understandable risk labels.',
    'Carla Mae Santos',
    2024,
    'Computer Science',
    array['Routing', 'Disaster Response', 'Mobile App', 'Risk Scoring'],
    array['Routing', 'Disaster Response', 'Mobile App', 'Risk Scoring'],
    'approved',
    93,
    now() - interval '145 days',
    now() - interval '145 days'
  ),
  (
    '10000000-0000-0000-0000-000000000005',
    'Capstone Topic Similarity Screening with Sentence Embeddings',
    'This project evaluates sentence-embedding techniques for screening proposed capstone titles against previously approved studies. The tool emphasizes fast similarity checks, explainable overlap indicators, and practical thresholds that faculty can use during early proposal review.',
    'Rhea Villanueva',
    2024,
    'Computer Science',
    array['NLP', 'Similarity Search', 'Embeddings', 'Academic Integrity'],
    array['NLP', 'Similarity Search', 'Embeddings', 'Academic Integrity'],
    'approved',
    95,
    now() - interval '140 days',
    now() - interval '140 days'
  ),
  (
    '10000000-0000-0000-0000-000000000006',
    'Clinic Queue Visibility System for Outpatient Student Services',
    'The research develops a queue visibility system for outpatient clinic services that lets students monitor current queue load, estimated waiting time, and service windows. It aims to reduce hallway congestion and improve time management for both patients and staff.',
    'Nicole Anne Reyes',
    2023,
    'Information Technology',
    array['Queue Management', 'Healthcare', 'Dashboard', 'Scheduling'],
    array['Queue Management', 'Healthcare', 'Dashboard', 'Scheduling'],
    'approved',
    88,
    now() - interval '135 days',
    now() - interval '135 days'
  ),
  (
    '10000000-0000-0000-0000-000000000007',
    'Energy Usage Analytics for Smart Classroom Air Conditioning',
    'This study proposes an energy analytics dashboard for classroom air-conditioning units using occupancy patterns and operating schedules. The system highlights inefficient runtime behavior and recommends control adjustments that can lower power usage without sacrificing comfort.',
    'Daniel C. Mendoza',
    2024,
    'Electrical Engineering',
    array['Energy Analytics', 'Smart Classroom', 'Efficiency', 'Monitoring'],
    array['Energy Analytics', 'Smart Classroom', 'Efficiency', 'Monitoring'],
    'approved',
    86,
    now() - interval '130 days',
    now() - interval '130 days'
  ),
  (
    '10000000-0000-0000-0000-000000000008',
    'Scholarship Eligibility Pre-Screening Using Rule-Based Evaluation',
    'The project creates a rule-based pre-screening system for scholarship applications that checks submitted records against published eligibility criteria. It reduces repetitive manual review by identifying missing requirements, incomplete fields, and likely-qualified applicants earlier in the process.',
    'Angela P. Torres',
    2023,
    'Business Administration',
    array['Decision Support', 'Scholarship', 'Rule Engine', 'Workflow'],
    array['Decision Support', 'Scholarship', 'Rule Engine', 'Workflow'],
    'approved',
    90,
    now() - interval '125 days',
    now() - interval '125 days'
  ),
  (
    '10000000-0000-0000-0000-000000000009',
    'Dormitory Incident Reporting with Severity-Based Escalation',
    'This research introduces an incident reporting system for dormitory operations that classifies reports by urgency, tracks response ownership, and records resolution times. The design focuses on accountability, resident transparency, and a clearer escalation path for critical incidents.',
    'Paolo Javier Lim',
    2024,
    'Information Technology',
    array['Incident Reporting', 'Escalation', 'Dormitory', 'Operations'],
    array['Incident Reporting', 'Escalation', 'Dormitory', 'Operations'],
    'pending',
    84,
    now() - interval '120 days',
    now() - interval '120 days'
  ),
  (
    '10000000-0000-0000-0000-000000000010',
    'Automated Resume Screening for Student Internship Matching',
    'The study examines a resume screening workflow for internship matching that scores applicants against role requirements using keyword coverage and structured profile data. It is designed as a triage tool for coordinators rather than a fully automated hiring decision engine.',
    'Shane Louise Bautista',
    2024,
    'Computer Science',
    array['Resume Screening', 'Matching', 'Internship', 'Scoring'],
    array['Resume Screening', 'Matching', 'Internship', 'Scoring'],
    'approved',
    92,
    now() - interval '115 days',
    now() - interval '115 days'
  ),
  (
    '10000000-0000-0000-0000-000000000011',
    'Library Seat Availability Monitoring through Occupancy Counters',
    'This project develops a library seat availability monitor using zone-level occupancy counters and a simple mobile-friendly dashboard. The goal is to help students find available study areas quickly while giving staff a clearer view of congestion patterns across the day.',
    'Katrina Joy Navarro',
    2023,
    'Information Technology',
    array['Library', 'Occupancy', 'Monitoring', 'Dashboard'],
    array['Library', 'Occupancy', 'Monitoring', 'Dashboard'],
    'approved',
    87,
    now() - interval '110 days',
    now() - interval '110 days'
  ),
  (
    '10000000-0000-0000-0000-000000000012',
    'Agricultural Supply Ordering Portal for Local Farming Cooperatives',
    'The research proposes an ordering portal that helps local farming cooperatives consolidate supply requests, compare delivery schedules, and track purchase status. It prioritizes easier coordination among members and fewer manual reconciliation errors in procurement records.',
    'Jerome Valdez',
    2024,
    'Business Administration',
    array['Procurement', 'Portal', 'Cooperative', 'Order Tracking'],
    array['Procurement', 'Portal', 'Cooperative', 'Order Tracking'],
    'needs_revision',
    82,
    now() - interval '105 days',
    now() - interval '105 days'
  ),
  (
    '10000000-0000-0000-0000-000000000013',
    'Vision-Based PPE Compliance Detection for Workshop Entrances',
    'This project studies a computer vision pipeline for checking whether students entering workshop spaces wear required protective equipment. The system is designed to support supervisors with entry-point reminders and logs rather than replace on-site safety judgment.',
    'Luis Miguel Ortega',
    2024,
    'Computer Science',
    array['Computer Vision', 'Safety', 'PPE', 'Detection'],
    array['Computer Vision', 'Safety', 'PPE', 'Detection'],
    'approved',
    94,
    now() - interval '100 days',
    now() - interval '100 days'
  ),
  (
    '10000000-0000-0000-0000-000000000014',
    'Visitor Analytics and Crowd Heatmaps for Campus Events',
    'The study creates an event analytics system that aggregates entrance scans and venue checkpoints to estimate crowd density and movement patterns. It aims to improve staffing decisions, entry flow management, and post-event planning for recurring campus programs.',
    'Patricia Gomez',
    2023,
    'Information Technology',
    array['Analytics', 'Heatmap', 'Events', 'Crowd Monitoring'],
    array['Analytics', 'Heatmap', 'Events', 'Crowd Monitoring'],
    'approved',
    88,
    now() - interval '95 days',
    now() - interval '95 days'
  ),
  (
    '10000000-0000-0000-0000-000000000015',
    'Early Warning Model for Student Attrition Using Enrollment Signals',
    'This research builds an early warning model for student attrition using attendance, payment timing, and subject load changes as indicators. The output is a risk-prioritized list intended to help advisers intervene earlier with students who may need support.',
    'Kimberly Grace Flores',
    2024,
    'Business Administration',
    array['Attrition', 'Early Warning', 'Education Analytics', 'Prediction'],
    array['Attrition', 'Early Warning', 'Education Analytics', 'Prediction'],
    'approved',
    91,
    now() - interval '90 days',
    now() - interval '90 days'
  ),
  (
    '10000000-0000-0000-0000-000000000016',
    'Waste Collection Scheduling Optimizer for Campus Facilities',
    'The project designs a scheduling optimizer for campus waste collection that groups pickup routes by bin fill trends, building activity, and service constraints. It is intended to reduce unnecessary trips while keeping high-traffic areas from overflowing during peak days.',
    'Bryan D. Castillo',
    2024,
    'Engineering',
    array['Scheduling', 'Optimization', 'Facilities', 'Waste Management'],
    array['Scheduling', 'Optimization', 'Facilities', 'Waste Management'],
    'approved',
    89,
    now() - interval '85 days',
    now() - interval '85 days'
  )
on conflict (id) do update
set
  title = excluded.title,
  abstract = excluded.abstract,
  author = excluded.author,
  year = excluded.year,
  department = excluded.department,
  tags = excluded.tags,
  keywords = excluded.keywords,
  status = excluded.status,
  "originalityScore" = excluded."originalityScore",
  updated_at = now();
